sovereigndefault_country_to_cca3 = {
    'Abu Dhabi': None, 'Albania': 'ALB', 'Algeria': 'DZA',
    'Andorra (Principality of)': 'AND', 'Angola': 'AGO', 'Anguilla': 'AIA',
    'Antigua & Barbuda': 'ATG', 'Argenti': 'ARG', 'Armenia': 'ARM', 'Aruba': 'ABW',
    'Australia': 'AUS', 'Austria': 'AUT', 'Azerbaijan': 'AZE', 'Bahamas': 'BHS',
    'Bahrain': 'BHR', 'Bangladesh': 'BGD', 'Barbados': 'BRB', 'Belarus': 'BLR',
    'Belgium': 'BEL', 'Belize': 'BLZ', 'Benin': 'BEN', 'Bermuda': 'BMU',
    'Bolivia': 'BOL', 'Bosnia and Herzegovi': 'BIH', 'Botswa': 'BWA', 'Brazil': 'BRA',
    'British Virgin Islands': 'VGB', 'Brunei': 'BRN', 'Bulgaria': 'BGR',
    'Burki Faso': 'BFA', 'Cambodia': 'KHM', 'Cameroon': 'CMR', 'Cada': 'CAN',
    'Cape Verde': 'CPV', 'Cayman Islands': 'CYM', 'Channel Islands': 'GGY',
    'Chile': 'CHL', 'Chi': 'CHN', 'Colombia': 'COL', 'Congo (Democratic Republic': 'COD',
    'Congo (Republic of)': 'COG', 'Cook Islands': 'COK', 'Costa Rica': 'CRI',
    'Croatia': 'HRV', 'Cuba': 'CUB', 'Curaçao': 'CUW', 'Cyprus': 'CYP',
    'Czech Republic': 'CZE', 'Denmark': 'DNK', 'Dominican Republic': 'DOM',
    'Ecuador': 'ECU', 'Egypt': 'EGY', 'El Salvador': 'SLV', 'Estonia': 'EST',
    'Ethiopia': 'ETH', 'Falkland Islands': 'FLK', 'Fiji': 'FJI', 'Finland': 'FIN',
    'France': 'FRA', 'French Guia': 'GUF', 'Gabon': 'GAB', 'Gambia': 'GMB',
    'Georgia': 'GEO', 'Germany': 'DEU', 'Gha': 'GHA', 'Gibraltar': 'GIB',
    'Greece': 'GRC', 'Greenland': 'GRL', 'Guatemala': 'GTM',
    'Guernsey (States of)': 'GGY', 'Guinea': 'GIN', 'Guinea-Bissau': 'GNB',
    'Guya': 'GUY', 'Haiti': 'HTI', 'Honduras': 'HND', 'Hong Kong': 'HKG',
    'Hungary': 'HUN', 'Iceland': 'ISL', 'India': 'IND', 'Indonesia': 'IDN',
    'Iran': 'IRN', 'Iraq': 'IRQ', 'Ireland': 'IRL', 'Isle of Man': 'IMN',
    'Israel': 'ISR', 'Italy': 'ITA', 'Ivory Coast': 'CIV', 'Jamaica': 'JAM',
    'Japan': 'JPN', 'Jersey (States of)': 'JEY', 'Jordan': 'JOR', 'Kazakhstan': 'KAZ',
    'Kenya': 'KEN', 'Korea, D.P.R.': 'PRK', 'Kuwait': 'KWT', 'Kyrgyzstan': 'KGZ',
    'Laos': 'LAO', 'Latvia': 'LVA', 'Lebanon': 'LBN', 'Liberia': 'LBR',
    'Libya': 'LBY', 'Liechtenstein': 'LIE', 'Lithuania': 'LTU', 'Luxembourg': 'LUX',
    'Macau': 'MAC', 'Macedonia': 'MKD', 'Madagascar': 'MDG', 'Malawi': 'MWI',
    'Malaysia': 'MYS', 'Maldives': 'MDV', 'Mali': 'MLI', 'Malta': 'MLT',
    'Martinique': 'MTQ', 'Mauritius': 'MUS', 'Mexico': 'MEX', 'Moldova': 'MDA',
    'Moco': 'MCO', 'Mongolia': 'MNG', 'Montenegro': 'MNE', 'Montserrat': 'MSR',
    'Morocco': 'MAR', 'Mozambique': 'MOZ', 'Myanmar': 'MMR', 'mibia': 'NAM',
    'Nepal': 'NPL', 'Netherlands': 'NLD', 'Netherlands Antilles': 'CUW',
    'New Zealand': 'NZL', 'Nicaragua': 'NIC', 'Niger': 'NER', 'Nigeria': 'NGA',
    'Norway': 'NOR', 'Oman': 'OMN', 'Pakistan': 'PAK', 'Palestinian Authority': 'PSE',
    'Pama': 'PAN', 'Papua New Guinea': 'PNG', 'Paraguay': 'PRY', 'Peru': 'PER',
    'Philippines': 'PHL', 'Poland': 'POL', 'Portugal': 'PRT', 'Qatar': 'QAT',
    'Ras Al Khaimah (Emirate of)': None, 'Reunion': 'REU', 'Romania': 'ROU',
    'Russia': 'RUS', 'Rwanda': 'RWA', 'Saint Lucia': 'LCA', 'Saudi Arabia': 'SAU',
    'Senegal': 'SEN', 'Serbia': 'SRB', 'Sharjah': None, 'Sierra Leone': 'SLE',
    'Singapore': 'SGP', 'Slovakia': 'SVK', 'Slovenia': 'SVN', 'Solomon Islands': 'SLB',
    'Somalia': 'SOM', 'South Africa': 'ZAF', 'South Korea': 'KOR', 'Spain': 'ESP',
    'Sri Lanka': 'LKA', 'St. Maarten': 'SXM', 'St. Vincent & the Gredines': 'VCT',
    'Sudan': 'SDN', 'Surime': 'SUR', 'Swaziland': 'SWZ', 'Sweden': 'SWE',
    'Switzerland': 'CHE', 'Syria': 'SYR', 'Taiwan': 'TWN', 'Tajikistan': 'TJK',
    'Tanzania': 'TZA', 'Thailand': 'THA', 'Togo': 'TGO', "Trinidad &' Tobago": 'TTO',
    'Tunisia': 'TUN', 'Turkey': 'TUR', 'Turks & Caicos Islands': 'TCA',
    'Uganda': 'UGA', 'Ukraine': 'UKR', 'United Arab Emirates': 'ARE',
    'United Kingdom': 'GBR', 'United States': 'USA', 'Uruguay': 'URY',
    'Uzbekistan': 'UZB', 'Venezuela': 'VEN', 'Vietm': 'VNM', 'Yemen': 'YEM',
    'Zambia': 'ZMB', 'Zimbabwe': 'ZWE', 'Congo (Democratic Republic of)': 'COD',
    'Curacao': 'CUW', 'Macao': 'MAC', 'Trinidad and Tobago': 'TTO',
    'Turks and Caicos Islands': 'TCA', 'Guernsey': 'GGY', 'Jersey': 'JEY',
    "Côte d'Ivoire": 'CIV', 'Korea': 'KOR', 'Yemen, Republic': 'YEM',
    'United States of America': 'USA', 'Andorra': 'AND',
    'Democratic Republic of Congo': 'COD', 'Ras Al Kamih': None,
    'Republic of the Congo': 'COG', 'Fiji Islands': 'FJI', 'Austria': 'AUT',
    'Belgium': 'BEL', 'Cyprus': 'CYP', 'Finland': 'FIN',
    'France': 'FRA', 'Germany': 'DEU', 'Greece': 'GRC',
    'Ireland': 'IRL', 'Italy': 'ITA', 'Luxembourg': 'LUX',
    'Malta': 'MLT', 'Netherlands': 'NLD', 'Portugal': 'PRT',
    'Slovenia': 'SVN', 'Spain': 'ESP', 'Turkmenistan': 'TKM',
    'Alderney (Channel Islands)': 'GGY', 'Bahamas-Offshore': 'BHS',
    'Bahrain-Offshore': 'BHR', 'Bosnia & Herzogovi': 'BIH', 'Eurozone': None,
    'Guernsey (Channel Islands)': 'GGY', 'Jersey (Channel Island)': 'JEY',
    'Pama-Offshore Banks': 'PAN', 'San Marino': 'SMR', 'Sark (Channel Islands)': 'GGY',
    'St. Vincent': 'VCT', 'Trinidad & Tobago': 'TTO'
}


country_similarity_country_to_cca3 = {
    'AFGHANISTAN': 'AFG', 'ALBANIA': 'ALB', 'ALGERIA': 'DZA', 'ANGOLA': 'AGO', 'ARGENTINA': 'ARG',
    'ARMENIA': 'ARM', 'AUSTRALIA': 'AUS', 'AUSTRIA': 'AUT', 'AZERBAIJAN': 'AZE',
    'BAHAMAS': 'BHS', 'BAHRAIN': 'BHR', 'BANGLADESH': 'BGD', 'BELARUS': 'BLR',
    'BELGIUM': 'BEL', 'BELIZE': 'BLZ', 'BENIN': 'BEN', 'BHUTAN': 'BTN',
    'BOLIVIA': 'BOL', 'BOSNIA': 'BIH', 'BOTSWANA': 'BWA', 'BRAZIL': 'BRA',
    'BRUNEI': 'BRN', 'BULGARIA': 'BGR', 'BURKINA FASO': 'BFA', 'BURUNDI': 'BDI',
    'CAMBODIA': 'KHM', 'CAMEROON': 'CMR', 'CANADA': 'CAN', 'CAPE VERDE': 'CPV',
    'CENT AFR REP': 'CAF', 'CHAD': 'TCD', 'CHILE': 'CHL', 'CHINA': 'CHN',
    'COLOMBIA': 'COL', 'COSTA RICA': 'CRI', 'CROATIA': 'HRV', 'CUBA': 'CUB',
    'CYPRUS': 'CYP', 'CZECHIA': 'CZE', 'DEM REP CONGO': 'COD', 'DENMARK': 'DNK',
    'DJIBOUTI': 'DJI', 'DOMINICAN REPUBLIC': 'DOM', 'EAST TIMOR': 'TLS',
    'ECUADOR': 'ECU', 'EGYPT': 'EGY', 'EL SALVADOR': 'SLV',
    'EQUAT. GUINEA': 'GNQ', 'ERITREA': 'ERI', 'ESTONIA': 'EST',
    'ESWATINI': 'SWZ', 'ETHIOPIA': 'ETH', 'FIJI': 'FJI', 'FINLAND': 'FIN',
    'FRANCE': 'FRA', 'GABON': 'GAB', 'GAMBIA': 'GMB', 'GEORGIA': 'GEO',
    'GERMANY': 'DEU', 'GHANA': 'GHA', 'GREAT BRITAIN': 'GBR', 'GREECE': 'GRC',
    'GUATEMALA': 'GTM', 'GUINEA': 'GIN', 'GUINEA BISSAU': 'GNB', 'GUYANA': 'GUY',
    'HAITI': 'HTI', 'HONDURAS': 'HND', 'HUNGARY': 'HUN', 'ICELAND': 'ISL',
    'INDIA': 'IND', 'INDONESIA': 'IDN', 'IRAN': 'IRN', 'IRAQ': 'IRQ',
    'IRELAND': 'IRL', 'ISRAEL': 'ISR', 'ITALY': 'ITA', 'IVORY COAST': 'CIV',
    'JAMAICA': 'JAM', 'JAPAN': 'JPN', 'JORDAN': 'JOR', 'KAZAKHSTAN': 'KAZ',
    'KENYA': 'KEN', 'KUWAIT': 'KWT', 'KYRGYZSTAN': 'KGZ', 'LAOS': 'LAO',
    'LATVIA': 'LVA', 'LEBANON': 'LBN', 'LESOTHO': 'LSO', 'LIBERIA': 'LBR',
    'LIBYA': 'LBY', 'LITHUANIA': 'LTU', 'LUXEMBOURG': 'LUX', 'MADAGASCAR': 'MDG',
    'MALAWI': 'MWI', 'MALAYSIA': 'MYS', 'MALI': 'MLI', 'MAURITANIA': 'MRT',
    'MAURITIUS': 'MUS', 'MEXICO': 'MEX', 'MOLDOVA': 'MDA', 'MONGOLIA': 'MNG',
    'MONTENEGRO': 'MNE', 'MOROCCO': 'MAR', 'MOZAMBIQUE': 'MOZ', 'MYANMAR': 'MMR',
    'NAMIBIA': 'NAM', 'NEPAL': 'NPL', 'NETHERLANDS': 'NLD',
    'NEW ZEALAND': 'NZL', 'NICARAGUA': 'NIC', 'NIGER': 'NER', 'NIGERIA': 'NGA',
    'NORTH KOREA': 'PRK', 'NORTH MACEDONIA': 'MKD', 'NORWAY': 'NOR', 'OMAN': 'OMN',
    'PAKISTAN': 'PAK', 'PANAMA': 'PAN', 'PAPUA NEW GUINEA': 'PNG',
    'PARAGUAY': 'PRY', 'PERU': 'PER', 'PHILIPPINES': 'PHL', 'POLAND': 'POL',
    'PORTUGAL': 'PRT', 'QATAR': 'QAT', 'REP CONGO': 'COG', 'ROMANIA': 'ROU',
    'RUSSIA': 'RUS', 'RWANDA': 'RWA', 'SAMOA': 'WSM', 'SAUDI ARABIA': 'SAU',
    'SENEGAL': 'SEN', 'SERBIA': 'SRB', 'SIERRA LEONE': 'SLE', 'SINGAPORE': 'SGP',
    'SLOVAKIA': 'SVK', 'SLOVENIA': 'SVN', 'SOLOMON ISLANDS': 'SLB',
    'SOMALIA': 'SOM', 'SOUTH AFRICA': 'ZAF', 'SOUTH KOREA': 'KOR',
    'SOUTH SUDAN': 'SSD', 'SPAIN': 'ESP', 'SRI LANKA': 'LKA', 'SUDAN': 'SDN',
    'SURINAME': 'SUR', 'SWEDEN': 'SWE', 'SWITZERLAND': 'CHE', 'SYRIA': 'SYR',
    'TAIWAN': 'TWN', 'TAJIKISTAN': 'TJK', 'TANZANIA': 'TZA', 'THAILAND': 'THA',
    'TOGO': 'TGO', 'TRINIDAD & TOBAGO': 'TTO', 'TUNISIA': 'TUN', 'TURKEY': 'TUR',
    'TURKMENISTAN': 'TKM', 'UGANDA': 'UGA', 'UKRAINE': 'UKR',
    'UNITED ARAB EMIRATES': 'ARE', 'UNITED STATES': 'USA', 'URUGUAY': 'URY',
    'UZBEKISTAN': 'UZB', 'VANUATU': 'VUT', 'VENEZUELA': 'VEN', 'VIETNAM': 'VNM',
    'YEMEN': 'YEM', 'ZAMBIA': 'ZMB', 'ZIMBABWE': 'ZWE'
}

imf_country_to_cca3 = {
    "Afghanistan": "AFG",
    "Albania": "ALB",
    "Algeria": "DZA",
    "Andorra": "AND",
    "Angola": "AGO",
    "Antigua and Barbuda": "ATG",
    "Argentina": "ARG",
    "Armenia": "ARM",
    "Aruba": "ABW",
    "Australia": "AUS",
    "Austria": "AUT",
    "Azerbaijan": "AZE",
    "Bahamas, The": "BHS",
    "Bahrain": "BHR",
    "Bangladesh": "BGD",
    "Barbados": "BRB",
    "Belarus": "BLR",
    "Belgium": "BEL",
    "Belize": "BLZ",
    "Benin": "BEN",
    "Bhutan": "BTN",
    "Bolivia": "BOL",
    "Bosnia and Herzegovina": "BIH",
    "Botswana": "BWA",
    "Brazil": "BRA",
    "Brunei Darussalam": "BRN",
    "Bulgaria": "BGR",
    "Burkina Faso": "BFA",
    "Burundi": "BDI",
    "Cabo Verde": "CPV",
    "Cambodia": "KHM",
    "Cameroon": "CMR",
    "Canada": "CAN",
    "Central African Republic": "CAF",
    "Chad": "TCD",
    "Chile": "CHL",
    "China, People's Republic of": "CHN",
    "Colombia": "COL",
    "Comoros": "COM",
    "Congo, Dem. Rep. of the": "COD",
    "Congo, Republic of ": "COG",  # Note the trailing space in the key
    "Costa Rica": "CRI",
    "Croatia": "HRV",
    "Cyprus": "CYP",
    "Czech Republic": "CZE",
    "Côte d'Ivoire": "CIV",
    "Denmark": "DNK",
    "Djibouti": "DJI",
    "Dominica": "DMA",
    "Dominican Republic": "DOM",
    "Ecuador": "ECU",
    "Egypt": "EGY",
    "El Salvador": "SLV",
    "Equatorial Guinea": "GNQ",
    "Eritrea": "ERI",
    "Estonia": "EST",
    "Eswatini": "SWZ",
    "Ethiopia": "ETH",
    "Fiji": "FJI",
    "Finland": "FIN",
    "France": "FRA",
    "Gabon": "GAB",
    "Gambia, The": "GMB",
    "Georgia": "GEO",
    "Germany": "DEU",
    "Ghana": "GHA",
    "Greece": "GRC",
    "Grenada": "GRD",
    "Guatemala": "GTM",
    "Guinea": "GIN",
    "Guinea-Bissau": "GNB",
    "Guyana": "GUY",
    "Haiti": "HTI",
    "Honduras": "HND",
    "Hong Kong SAR": "HKG",
    "Hungary": "HUN",
    "Iceland": "ISL",
    "India": "IND",
    "Indonesia": "IDN",
    "Iran": "IRN",
    "Iraq": "IRQ",
    "Ireland": "IRL",
    "Israel": "ISR",
    "Italy": "ITA",
    "Jamaica": "JAM",
    "Japan": "JPN",
    "Jordan": "JOR",
    "Kazakhstan": "KAZ",
    "Kenya": "KEN",
    "Kiribati": "KIR",
    "Korea, Republic of": "KOR",
    "Kosovo": "XKX",  # Unofficial ISO code
    "Kuwait": "KWT",
    "Kyrgyz Republic": "KGZ",
    "Lao P.D.R.": "LAO",
    "Latvia": "LVA",
    "Lebanon": "LBN",
    "Lesotho": "LSO",
    "Liberia": "LBR",
    "Libya": "LBY",
    "Lithuania": "LTU",
    "Luxembourg": "LUX",
    "Macao SAR": "MAC",
    "Madagascar": "MDG",
    "Malawi": "MWI",
    "Malaysia": "MYS",
    "Maldives": "MDV",
    "Mali": "MLI",
    "Malta": "MLT",
    "Marshall Islands": "MHL",
    "Mauritania": "MRT",
    "Mauritius": "MUS",
    "Mexico": "MEX",
    "Micronesia, Fed. States of": "FSM",
    "Moldova": "MDA",
    "Mongolia": "MNG",
    "Montenegro": "MNE",
    "Morocco": "MAR",
    "Mozambique": "MOZ",
    "Myanmar": "MMR",
    "Namibia": "NAM",
    "Nauru": "NRU",
    "Nepal": "NPL",
    "Netherlands": "NLD",
    "New Zealand": "NZL",
    "Nicaragua": "NIC",
    "Niger": "NER",
    "Nigeria": "NGA",
    "North Macedonia ": "MKD",  # Note the trailing space in the key
    "Norway": "NOR",
    "Oman": "OMN",
    "Pakistan": "PAK",
    "Palau": "PLW",
    "Panama": "PAN",
    "Papua New Guinea": "PNG",
    "Paraguay": "PRY",
    "Peru": "PER",
    "Philippines": "PHL",
    "Poland": "POL",
    "Portugal": "PRT",
    "Puerto Rico": "PRI",
    "Qatar": "QAT",
    "Romania": "ROU",
    "Russian Federation": "RUS",
    "Rwanda": "RWA",
    "Saint Kitts and Nevis": "KNA",
    "Saint Lucia": "LCA",
    "Saint Vincent and the Grenadines": "VCT",
    "Samoa": "WSM",
    "San Marino": "SMR",
    "Saudi Arabia": "SAU",
    "Senegal": "SEN",
    "Serbia": "SRB",
    "Seychelles": "SYC",
    "Sierra Leone": "SLE",
    "Singapore": "SGP",
    "Slovak Republic": "SVK",
    "Slovenia": "SVN",
    "Solomon Islands": "SLB",
    "Somalia": "SOM",
    "South Africa": "ZAF",
    "South Sudan, Republic of": "SSD",
    "Spain": "ESP",
    "Sri Lanka": "LKA",
    "Sudan": "SDN",
    "Suriname": "SUR",
    "Sweden": "SWE",
    "Switzerland": "CHE",
    "Syria": "SYR",
    "São Tomé and Príncipe": "STP",
    "Taiwan Province of China": "TWN",
    "Tajikistan": "TJK",
    "Tanzania": "TZA",
    "Thailand": "THA",
    "Timor-Leste": "TLS",
    "Togo": "TGO",
    "Tonga": "TON",
    "Trinidad and Tobago": "TTO",
    "Tunisia": "TUN",
    "Turkmenistan": "TKM",
    "Tuvalu": "TUV",
    "Türkiye, Republic of": "TUR",
    "Uganda": "UGA",
    "Ukraine": "UKR",
    "United Arab Emirates": "ARE",
    "United Kingdom": "GBR",
    "United States": "USA",
    "Uruguay": "URY",
    "Uzbekistan": "UZB",
    "Vanuatu": "VUT",
    "Venezuela": "VEN",
    "Vietnam": "VNM",
    "West Bank and Gaza": "PSE",
    "Yemen": "YEM",
    "Zambia": "ZMB",
    "Zimbabwe": "ZWE",
    # Regional and group entries (no ISO 3166‑1 codes; set to "N/A")
    "Africa (Region)": "N/A",
    "Asia and Pacific": "N/A",
    "Australia and New Zealand": "N/A",
    "Caribbean": "N/A",
    "Central America": "N/A",
    "Central Asia and the Caucasus": "N/A",
    "East Asia": "N/A",
    "Eastern Europe ": "N/A",
    "Europe": "N/A",
    "Middle East (Region)": "N/A",
    "North Africa": "N/A",
    "North America": "N/A",
    "Pacific Islands ": "N/A",
    "South America": "N/A",
    "South Asia": "N/A",
    "Southeast Asia": "N/A",
    "Sub-Saharan Africa (Region) ": "N/A",
    "Western Europe": "N/A",
    "Western Hemisphere (Region)": "N/A",
    "ASEAN-5": "N/A",
    "Advanced economies": "N/A",
    "Emerging and Developing Asia": "N/A",
    "Emerging and Developing Europe": "N/A",
    "Emerging market and developing economies": "N/A",
    "Euro area": "N/A",
    "European Union": "N/A",
    "Latin America and the Caribbean": "N/A",
    "Major advanced economies (G7)": "N/A",
    "Middle East and Central Asia": "N/A",
    "Other advanced economies": "N/A",
    "Sub-Saharan Africa": "N/A",
    "World": "N/A"
}
